# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  WORKSPACE: '$(system.defaultWorkingDirectory)' # Current workspace
  ANDROID_VERSION: 'cm-14.1' # Default branch

steps:
- script: |
    sudo apt-get update --fix-missing
  displayName: 'Update our repos!'

- script: |
    mkdir ~/bin && curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && sudo chmod a+x ~/bin/repo && export PATH="$HOME/bin:$PATH"
  displayName: 'Downloading repo from google'
  
- script: |
    sudo apt-get install -y g++ zip ccache gcc make libfl-dev libncurses5-dev flex bc kmod
  displayName: 'Downloading kernel build dependencies'

- script: |
    sudo apt-get install -y build-essential g++-multilib gcc-multilib gperf imagemagick lib32ncurses5-dev lib32readline6-dev lib32z1-dev libesd0-dev liblz4-tool libsdl1.2-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zlib1g-dev rsync autoconf automake perl
    mkdir $WORKSPACE/android-dependencies && git clone https://github.com/bitrvmpd/jenkins-android-build.git --depth=1 $WORKSPACE/android-dependencies/jenkins-android-build
    sudo mv $WORKSPACE/android-dependencies/jenkins-android-build/libfl.so.2.0.0 /usr/lib/.
    sudo ln -s /usr/lib/libfl.so.2.0.0 /usr/lib/libfl.so
    sudo ln -s /usr/lib/libfl.so.2.0.0 /usr/lib/libfl.so.2
  displayName: 'Downloading ROM build dependencies'

- script: |
    cd $WORKSPACE
    repo init -u git://github.com/bitrvmpd/android.git -b $ANDROID_VERSION --depth=1
    repo sync -c -n -j 1 --force-sync && python /usr/bin/repo sync -c -l -j 16
  displayName: 'Syncing sources'

- script: |
    cd $WORKSPACE
    bash loup/tools/build.sh santoni
  displayName: 'Build santoni'
  
- script: |
    cd $WORKSPACE
    bash loup/tools/build.sh ether
  displayName: 'Build ether'

- script: |
    ls -lah $WORKSPACE
  displayName: 'List all the things!'
