# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    sudo apt-get update
  displayName: 'Update our repos!'

- script: |
    sudo apt-get install -y g++ zip ccache gcc make libfl-dev libncurses5-dev flex bc kmod
  displayName: 'Downloading kernel build dependencies'

- script: |
    sudo apt-get install -y build-essential g++-multilib gcc-multilib gperf imagemagick lib32ncurses5-dev lib32readline6-dev lib32z1-dev libesd0-dev liblz4-tool libsdl1.2-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zlib1g-dev rsync autoconf automake perl
  displayName: 'Downloading ROM build dependencies'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script 2'
